swagger: '2.0'
info:
  description: RESTful API for Global ID service
  version: 0.0.2
  title: Global ID service
host: to.be.defined
basePath: /v1
tags:
  - name: gid
    description: APIs for GID service
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - https
paths:
  /gid:
    post:
      tags:
        - gid
      summary: Add a new GID
      description: Add a new GID.
      operationId: addGID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: GID object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/GID'
      responses:
        '405':
          description: Invalid input
  '/gid/{GID}':
    get:
      tags:
        - gid
      summary: Query data by GID
      description: Returns a single GID data
      operationId: getGIDById
      produces:
        - application/json
      parameters:
        - name: GID
          in: path
          description: Global ID to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/GID'
        '404':
          description: GID not found
    post:
      tags:
        - gid
      summary: Updates GID data
      description: Updates GID data.
      operationId: updateGID
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: GID
          in: path
          description: GID needs to be updated
          required: true
          type: string
        - in: body
          name: body
          description: GID data to be updated
          required: true
          schema:
            $ref: '#/definitions/GID'
      responses:
        '200':
          schema:
            type: object
            properties:
              result:
                type: string
                example: Ok
          description: Update done
        '405':
          description: Invalid input
    delete:
      tags:
        - gid
      summary: Deletes specified GID
      description: Deletes specified GID.
      operationId: deleteGID
      produces:
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: GID
          in: path
          description: GID to delete
          required: true
          type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              result:
                type: string
                example: Ok
          description: Delete done
        '400':
          description: Invalid GID supplied or GID has child.
        '404':
          description: GID not found
  '/gid/{GID}/parent':
    get:
      tags:
        - gid
      summary: Returns parent GID of specified GID
      description: 
        Returns parent GID of specified GID. If no parent, returns {}.
      operationId: getParentGID
      produces:
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: GID
          in: path
          description: GID to get parent
          required: true
          type: string
      responses:
        '200':
          description: 
            successful operation. 
          schema:
            $ref: '#/definitions/GID'
        '404':
          description: GID not found
  '/gid/{GID}/children':
    get:
      tags:
        - gid
      summary: Returns all child GID list of specified GID
      description: Returns all child GID list of specified GID. If no child, returns {}.
      operationId: getChildGIDList
      produces:
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: GID
          in: path
          description: GID to get children
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              children:
                type: array
                items:
                  type: string
                  format: 64byte
        '404':
          description: GID not found
  '/gid/{GID}/devices':
    get:
      tags:
        - gid
      summary: Returns all child device GID list of specified GID
      description: Returns all child device GID list of specified GID. If no child device, return {}.
      operationId: getDeviceGIDList
      produces:
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: GID
          in: path
          description: GID to get devices
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              devices:
                type: array
                items:
                  type: string
                  format: 64byte
        '404':
          description: GID not found
  # '/gid/{GID}/wallets':
  #   get:
  #     tags:
  #       - gid
  #     summary: Returns all wallet GID list of specified GID
  #     description: Returns all wallet GID list of specified GID. If no wallet, return {}.
  #     operationId: getWalletGIDList
  #     produces:
  #       - application/json
  #     parameters:
  #       - name: api_key
  #         in: header
  #         required: false
  #         type: string
  #       - name: GID
  #         in: path
  #         description: GID to get wallets
  #         required: true
  #         type: string
  #     responses:
  #       '200':
  #         description: successful operation
  #         schema:
  #           type: object
  #           properties:
  #             wallets:
  #               type: array
  #               items:
  #                 type: string
  #                 format: 64byte
  #       '404':
  #         description: GID not found
definitions:
  GID:
    type: object
    properties:
      gid:
        type: string
        format: 64byte
      type:
        type: string
        enum:
          - person
          - device
          - wallet
          - group
          - etc.
      parent:
        type: string
      children:
        type: array
        items:
          type: string
          format: 64byte
      metadata:
        type: object
        description: Data of GID
